version: "3"

services:

    nginx:
        image: nginx
        volumes:
            - ./app-a/build/:/usr/share/nginx/html/app-a
            - ./app-b/build/:/usr/share/nginx/html/app-b
            - ./panel/build/:/usr/share/nginx/html/
        ports:
        - "80:80"
        environment:
        - NGINX_PORT=80